INSERT INTO SHIP_TYPE (NAME, MEAN_SPEED, SPEED_DEVIATION, MEAN_POWER,
POWER_DEVIATION, MEAN_TONNAGE, TONNAGE_DEVIATION)
values('BigShip', 1, 1, 5, 1, 100, 50);

INSERT INTO PORT (X, Y, NAME, OWNER) values(0, 0, 'Port o Prince', 1);
INSERT INTO PORT (X, Y, NAME, OWNER) values(20, 0, 'Britains base', 1);
INSERT INTO PORT (X, Y, NAME, OWNER) values(0, 40, 'Spains base', 2);
INSERT INTO PORT (X, Y, NAME, OWNER) values(20, 40, 'Martinica', 2);
INSERT INTO PORT (X, Y, NAME, OWNER) values(10, 20, 'Cuba', 2);
